version: '3.5'

services:

  todo-db:
    image: quay.io/andrewazores/demo-postgres:1.0
    build:
        context: demo-postgres/
        dockerfile: Dockerfile
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=todouser
     - POSTGRES_PASSWORD=todopw
     - POSTGRES_DB=tododb
    privileged: true

  example-service:
    image: quay.io/andrewazores/flight-recorder-example-service:1.2
    build:
      context: example-service/
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    ports:
      - 8080:8080
      - 9091:9091
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://todo-db:5432/tododb
    links:
      - todo-db
