version: '3.5'

services:

# container-jfr:
#   hostname: container-jfr
#   image: quay.io/andrewazores/container-jfr:0.21.0
#   ports:
#     - 9092:9092
#     - 8181:8181
#   environment:
#     - CONTAINER_JFR_RJMX_PORT=9092
#     - CONTAINER_JFR_RMI_PORT=9092
#     - CONTAINER_JFR_WEB_HOST=0.0.0.0
#     - CONTAINER_JFR_RJMX_USER=user
#     - CONTAINER_JFR_RJMX_PASS=pass
#   links:
#     - example-service

  todo-db:
    hostname: todo-db
    image: quay.io/andrewazores/demo-postgres:1.0
    build:
      context: demo-postgres/
      dockerfile: Dockerfile
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=todouser
     - POSTGRES_PASSWORD=todopw
     - POSTGRES_DB=tododb
    privileged: true

  example-service:
    hostname: example-service
    image: quay.io/andrewazores/flight-recorder-example-service:1.3
    build:
      context: example-service/
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    ports:
      - 8080:8080
      - 9091:9091
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://todo-db:5432/tododb
    links:
      - todo-db
