apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert -f container-compose.yaml --provider=openshift
      --out=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: example-service
  name: example-service
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9091"
    port: 9091
    targetPort: 9091
  selector:
    io.kompose.service: example-service
status:
  loadBalancer: {}
