apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: example-service
  name: example-service
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/andrewazores/flight-recorder-example-service:1.0
    generation: null
    importPolicy: {}
    name: "1.0"
status:
  dockerImageRepository: ""
