apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose -v convert -f container-compose.yaml --provider=openshift
      --out=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: example-service
  name: example-service
spec:
  replicas: 1
  selector:
    io.kompose.service: example-service
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: example-service
    spec:
      containers:
      - env:
        - name: QUARKUS_DATASOURCE_URL
          value: jdbc:postgresql://todo-db:5432/tododb
        image: ' '
        name: example-service
        ports:
        - containerPort: 8080
        - containerPort: 9091
        resources: {}
      hostname: example-service
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - example-service
      from:
        kind: ImageStreamTag
        name: example-service:1.2
    type: ImageChange
status: {}
