apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: dpage/pgadmin4
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
