apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose -v convert -f container-compose.yaml --provider=openshift
      --volumes hostPath --out=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    io.kompose.service: prometheus
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/flight-recorder-network: "true"
        io.kompose.service: prometheus
    spec:
      containers:
      - image: ' '
        name: prometheus
        ports:
        - containerPort: 9090
        resources: {}
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-hostpath0
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/andrew/workspace/jfr-custom-events/prometheus.yml
        name: prometheus-hostpath0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - prometheus
      from:
        kind: ImageStreamTag
        name: prometheus:latest
    type: ImageChange
status: {}
