apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: todo-db
  name: todo-db
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/andrewazores/demo-postgres:1.0
    generation: null
    importPolicy: {}
    name: "1.0"
status:
  dockerImageRepository: ""
