apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: todo-db
  name: todo-db
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: postgres:11
    generation: null
    importPolicy: {}
    name: "11"
status:
  dockerImageRepository: ""
