apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose -v convert -f container-compose.yaml --provider=openshift
      --volumes hostPath --out=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-db
  name: todo-db
spec:
  replicas: 1
  selector:
    io.kompose.service: todo-db
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/flight-recorder-network: "true"
        io.kompose.service: todo-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: tododb
        - name: POSTGRES_PASSWORD
          value: todopw
        - name: POSTGRES_USER
          value: todouser
        image: ' '
        name: todo-db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          name: todo-db-hostpath0
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /home/andrew/workspace/jfr-custom-events/init.sql
        name: todo-db-hostpath0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - todo-db
      from:
        kind: ImageStreamTag
        name: todo-db:11
    type: ImageChange
status: {}
