apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vertx-fib-demo
  name: vertx-fib-demo
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: quay.io/andrewazores/vertx-fib-demo:0.2.0
    generation: null
    importPolicy: {}
    name: 0.2.0
status:
  dockerImageRepository: ""
