apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -v convert -f container-compose.yaml --provider=openshift
      --out=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vertx-fib-demo
  name: vertx-fib-demo
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8080
  - name: "jfr-jmx"
    port: 9093
    targetPort: 9093
  selector:
    io.kompose.service: vertx-fib-demo
status:
  loadBalancer: {}
